---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop
  namespace: vulnerable-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juice-shop
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      containers:
        - name: juice-shop
          image: bkimminich/juice-shop
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: juice-shop-service
  namespace: vulnerable-apps
spec:
  type: NodePort
  selector:
    app: juice-shop
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30081
