apiVersion: apps/v1
kind: Deployment
metadata:
  name: vampi
  namespace: vulnerable-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vampi
  template:
    metadata:
      labels:
        app: vampi
    spec:
      containers:
        - name: vampi
          image: erev0s/vampi:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: vampi-service
  namespace: vulnerable-apps
spec:
  type: NodePort
  selector:
    app: vampi
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30083
