- name: Read AWS credentials from iooding profile
  set_fact:
    aws_creds: "{{ lookup('ini', 'aws_access_key_id section=iooding file=' + lookup('env', 'HOME') + '/.aws/credentials') }}"
    aws_secret: "{{ lookup('ini', 'aws_secret_access_key section=iooding file=' + lookup('env', 'HOME') + '/.aws/credentials') }}"

- name: Create AWS iooding namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: iooding
  run_once: true

- name: Create AWS credentials secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: aws-credentials
        namespace: iooding
      type: Opaque
      stringData:
        access_key_id: "{{ aws_creds }}"
        secret_access_key: "{{ aws_secret }}"

- name: Wait for webhook pods ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: external-secrets
    label_selectors:
      - app.kubernetes.io/name=external-secrets-webhook
  register: webhook_pods
  until: webhook_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length > 0
  retries: 30
  delay: 10
  changed_when: false

- name: Create SecretStore for AWS SSM
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: external-secrets.io/v1
      kind: SecretStore
      metadata:
        name: aws-ssm
        namespace: iooding
      spec:
        provider:
          aws:
            service: ParameterStore
            region: eu-central-1
            auth:
              secretRef:
                accessKeyIDSecretRef:
                  name: aws-credentials
                  key: access_key_id
                secretAccessKeySecretRef:
                  name: aws-credentials
                  key: secret_access_key
