---
- name: Define node-specific variables
  ansible.builtin.set_fact:
    etcd_data_dir: "{{ '/root/k8s-etcd' if 'k8s_masters' in group_names else ansible_env.HOME + '/k8s-etcd' }}"
    become_for_task: "{{ 'yes' if 'k8s_masters' in group_names else 'no' }}"

- name: Ensure etcd directories exist
  ansible.builtin.file:
    path: "{{ etcd_data_dir }}/{{ item }}"
    state: directory
    mode: "0755"
  become: "{{ become_for_task }}"
  loop:
    - certs
    - data

- name: Distribute etcd certificates to each node
  ansible.builtin.copy:
    src: "/tmp/k8s-etcd-certs/{{ item }}"
    dest: "{{ etcd_data_dir }}/certs/{{ item }}"
    mode: "0644"
  become: "{{ become_for_task }}"
  loop:
    - ca.crt
    - "{{ inventory_hostname }}.crt"
    - "{{ inventory_hostname }}.key"
    - "{{ inventory_hostname }}-peer.crt"
    - "{{ inventory_hostname }}-peer.key"
  notify: restart etcd

- name: Deploy etcd docker-compose template
  ansible.builtin.template:
    src: files/kubernetes/etcd-docker-compose.yml.j2
    dest: "{{ etcd_data_dir }}/docker-compose.yml"
    mode: "0644"
  become: "{{ become_for_task }}"
  notify: restart etcd

- name: Check if Docker Compose is available
  ansible.builtin.command:
    cmd: which docker-compose
  register: docker_compose_check
  failed_when: false
  changed_when: false

- name: Start etcd container
  ansible.builtin.command:
    cmd: "{{ 'docker-compose' if docker_compose_check.rc == 0 else 'docker compose' }} up -d --remove-orphans"
    chdir: "{{ etcd_data_dir }}"
  become: "{{ become_for_task }}"
  changed_when: false
