---
- name: Explicitly gather facts
  setup:
    gather_subset:
      - "network"

- name: Install HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Configure HAProxy
  template:
    src: files/haproxy/haproxy.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Ensure HAProxy is enabled and started
  systemd:
    name: haproxy
    enabled: yes
    state: restarted
    daemon_reload: yes
