---
- name: Install Helm
  ansible.builtin.shell:
    cmd: "curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
  args:
    creates: /usr/local/bin/helm

- name: Add Helm repos
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop:
    - { name: rook-release, url: "https://charts.rook.io/release" }
    - {
        name: prometheus-community,
        url: "https://prometheus-community.github.io/helm-charts",
      }
    - { name: ingress-nginx, url: "https://kubernetes.github.io/ingress-nginx" }
    - { name: external-secrets, url: "https://charts.external-secrets.io" }
  run_once: true

- name: Update Helm repos
  ansible.builtin.shell:
    cmd: /usr/local/bin/helm repo update
  run_once: true
