---
- name: Install Prometheus Operator
  kubernetes.core.helm:
    name: prometheus
    namespace: monitoring
    create_namespace: true
    chart_ref: prometheus-community/kube-prometheus-stack
    timeout: 15m
    values:
      grafana:
        adminPassword: "{{ grafana_admin_password }}"
      prometheus:
        prometheusSpec:
          serviceMonitorSelectorNilUsesHardcodedSelector: false

- name: Create Grafana NodePort services
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: grafana-nodeport
        namespace: monitoring
      spec:
        type: NodePort
        selector:
          app.kubernetes.io/name: grafana
        ports:
          - port: 80
            targetPort: 3000
            nodePort: 30000

- name: Create Prometheus NodePort services
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: prometheus-nodeport
        namespace: monitoring
      spec:
        type: NodePort
        selector:
          app.kubernetes.io/name: prometheus
        ports:
          - port: 9090
            targetPort: 9090
            nodePort: 30001
