---
- name: Check if node is in cluster
  kubernetes.core.k8s_info:
    kind: Node
    name: "{{ inventory_hostname }}"
  register: node_check
  delegate_to: "{{ groups['k8s_masters'] | first }}"
  ignore_errors: true

- name: Get join command
  shell: kubeadm token create --print-join-command
  register: join_cmd
  delegate_to: "{{ groups['k8s_masters'] | first }}"
  when: node_check.resources | length == 0

- name: Join cluster
  command: "{{ join_cmd.stdout }}"
  when: node_check.resources | length == 0

- name: Wait for node ready
  kubernetes.core.k8s_info:
    kind: Node
    name: "{{ inventory_hostname }}"
  register: node_status
  delegate_to: "{{ groups['k8s_masters'] | first }}"
  until: >-
    node_status.resources[0].status.conditions |
    selectattr('type', 'equalto', 'Ready') |
    map(attribute='status') | first == 'True'
  retries: 30
  delay: 10
  when: node_check.resources | length == 0
