---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
  namespace: vulnerable-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
        - name: webgoat
          image: webgoat/webgoat
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webgoat-service
  namespace: vulnerable-apps
spec:
  type: NodePort
  selector:
    app: webgoat
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
