---
- name: Create .kube directory
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0750"
  with_items:
    - "{{ user_home }}/.kube"
    - "/root/.kube"

- name: Wait for admin.conf on first master
  wait_for:
    path: /etc/kubernetes/admin.conf
    state: present
    timeout: 300
  when: inventory_hostname == groups['k8s_masters'][0]

- name: Ensure first master is ready before proceeding
  wait_for:
    timeout: 30
  when: inventory_hostname != groups['k8s_masters'][0]

- name: Copy admin.conf from first master
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /etc/kubernetes/admin.conf
    remote_src: yes
  delegate_to: "{{ groups['k8s_masters'][0] }}"
  when: inventory_hostname != groups['k8s_masters'][0]

- name: Copy admin.conf to kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ item }}"
    remote_src: yes
    owner: "{{ 'ubuntu' if 'home' in item else 'root' }}"
    group: "{{ 'ubuntu' if 'home' in item else 'root' }}"
    mode: "0600"
  with_items:
    - "{{ user_home }}/.kube/config"
    - "/root/.kube/config"
