---
- name: Create .kube directory
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0750"
  with_items:
    - "{{ user_home }}/.kube"
    - "/root/.kube"

- name: Wait for admin.conf to exist on master-1
  wait_for:
    path: /etc/kubernetes/admin.conf
    state: present
    timeout: 300
  when: inventory_hostname == 'master-1'

- name: Synchronize admin.conf from master-1 to other masters
  synchronize:
    src: /etc/kubernetes/admin.conf
    dest: /etc/kubernetes/admin.conf
    mode: pull
  delegate_to: "{{ item }}"
  when: inventory_hostname != 'master-1'
  loop: "{{ groups['k8s_masters'] | difference(['master-1']) }}"

- name: Copy admin.conf to user's kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ item }}"
    remote_src: yes
    owner: "{{ 'ubuntu' if 'home' in item else 'root' }}"
    group: "{{ 'ubuntu' if 'home' in item else 'root' }}"
    mode: "0600"
  with_items:
    - "{{ user_home }}/.kube/config"
    - "/root/.kube/config"
