---
- name: Prepare Cluster Nodes
  hosts: k8s_cluster
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Include cluster preparation tasks
      include_tasks: tasks/cluster-preparation.yml
    - name: Include common Kubernetes setup
      include_tasks: tasks/common.yml

- name: Setup External Etcd Cluster
  hosts: etcd_nodes
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  vars:
    etcd_pki_dir: "{{ '/root/etcd_pki' if 'k8s_masters' in group_names else ansible_env.HOME + '/etcd_pki' }}"
    etcd_primary_node: "{{ groups['etcd_nodes'][0] }}"
  tasks:
    - name: Include etcd certificate generation and fetching
      include_tasks: tasks/etcd-setup.yml
    - name: Include etcd service deployment
      include_tasks: tasks/etcd-service.yml
  handlers:
    - name: restart etcd
      ansible.builtin.command:
        cmd: "{{ 'docker-compose' if docker_compose_check.rc == 0 else 'docker compose' }} restart"
        chdir: "{{ etcd_data_dir }}"
      become: "{{ become_for_task }}"

- name: Setup Load Balancers
  hosts: load_balancers
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  tags:
    - configure_masters
  tasks:
    - name: Include Keepalived setup
      include_tasks: tasks/keepalived.yml
    - name: Include HAProxy setup
      include_tasks: tasks/haproxy.yml

- name: Initialize First Master
  hosts: "{{ groups['k8s_masters'][0] }}"
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Include first master initialization
      include_tasks: tasks/master-init.yml

- name: Setup Other Kubernetes Masters
  hosts: k8s_masters:!{{ groups['k8s_masters'][0] }}
  gather_facts: yes
  become: yes
  serial: 1
  vars_files:
    - vars.yml
  tasks:
    - name: Wait for first master to be ready
      ansible.builtin.wait_for:
        port: 6443
        host: "{{ hostvars[groups['k8s_masters'][0]]['ansible_default_ipv4']['address'] }}"
        delay: 30
        timeout: 300
    - name: Include Master join
      include_tasks: tasks/master-join.yml

- name: Configure All Kubernetes Masters
  hosts: k8s_masters
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Include Kubeconfig setup
      include_tasks: tasks/kubeconfig.yml
    - name: Configure Masters Controller Manager
      include_tasks: tasks/kube-controller-manager.yml
    - name: Configure Masters Apiserver
      include_tasks: tasks/kube-apiserver.yml

- name: Deploy CNI and RBAC from First Master
  hosts: "{{ groups['k8s_masters'][0] }}"
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Include Calico setup
      include_tasks: tasks/calico.yml
    - name: Configure Masters RBAC
      include_tasks: tasks/rbac.yml

- name: Setup Kubernetes Workers
  hosts: k8s_workers
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Wait for masters to be available
      ansible.builtin.wait_for:
        port: 6443
        host: "{{ hostvars[groups['k8s_masters'][0]]['ansible_default_ipv4']['address'] }}"
        delay: 10
        timeout: 300
    - name: Include worker join
      include_tasks: tasks/worker-join.yml

- name: Setup Kubernetes Monitoring
  hosts: "{{ groups['k8s_masters'][0] }}"
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  tags:
    - configure_masters
  tasks:
    - name: Include Helm Installation
      include_tasks: tasks/helm.yml
    - name: Include Prometheus Operator configuration
      include_tasks: tasks/monitoring.yml
