---
- name: Prepare Kubernetes Cluster
  hosts: k8s_cluster
  gather_facts: yes
  gather_timeout: 60
  become: yes
  pre_tasks:
    - name: Wait for cloud-init to complete properly
      command: cloud-init status --wait
      register: cloudinit_status
      retries: 10
      delay: 60
      until: cloudinit_status.rc == 0
      changed_when: false

- name: Install Common Kubernetes Components
  hosts: k8s_cluster
  gather_facts: yes
  gather_timeout: 60
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Include common Kubernetes setup
      include_tasks: tasks/common.yml

- name: Setup Load Balancers
  hosts: load_balancers
  gather_facts: yes
  gather_timeout: 60
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Include Keepalived setup
      include_tasks: tasks/keepalived.yml

    - name: Include HAProxy setup
      include_tasks: tasks/haproxy.yml

- name: Setup Kubernetes Masters
  hosts: k8s_masters
  gather_facts: yes
  gather_timeout: 60
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Include Master initialization
      include_tasks: tasks/master-init.yml
      when: inventory_hostname == "master-1"

    - name: Include Master join
      include_tasks: tasks/master-join.yml
      when:
        - inventory_hostname in groups['k8s_masters']
        - inventory_hostname != "master-1"

    - name: Include Kubeconfig setup
      include_tasks: tasks/kubeconfig.yml
      when: inventory_hostname in groups['k8s_masters']

    - name: Include Calico setup
      include_tasks: tasks/calico.yml
      when: inventory_hostname in groups['k8s_masters']

- name: Configure Kubernetes Masters
  hosts: k8s_masters
  gather_facts: yes
  gather_timeout: 60
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Configure Masters Controller Manager
      include_tasks: tasks/kube-controller-manager.yml

    - name: Configure Masters Apiserver
      include_tasks: tasks/kube-apiserver.yml

- name: Setup Kubernetes Workers
  hosts: k8s_workers
  gather_facts: yes
  gather_timeout: 60
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Include worker join
      include_tasks: tasks/worker-join.yml

- name: Configure Kubernetes Masters RBAC
  hosts: k8s_masters
  gather_facts: yes
  gather_timeout: 60
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Configure Masters RBAC
      include_tasks: tasks/rbac.yml

- name: Setup Kubernetes Monitoring
  hosts: k8s_masters
  gather_facts: yes
  gather_timeout: 60
  become: yes
  vars_files:
    - vars.yml
  tags:
    - configure_masters
  tasks:
    - name: Include Helm Installation
      include_tasks: tasks/helm2.yml

    - name: Include Prometheus Operator configuration
      include_tasks: tasks/monitoring2.yml
