---
- name: Check if already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_config

- name: Get join credentials from first master
  set_fact:
    master_join_command: "{{ hostvars[groups['k8s_masters'][0]].master_join_command | default('') }}"
    cert_key: "{{ hostvars[groups['k8s_masters'][0]].cert_key | default('') }}"
  when: not kubelet_config.stat.exists

- name: Join control plane
  command: "{{ master_join_command }} --control-plane --certificate-key {{ cert_key }}"
  when:
    - not kubelet_config.stat.exists
    - master_join_command != ''
    - cert_key != ''
  async: 300
  poll: 15
  register: join_result
  retries: 3
  delay: 30
  until: join_result.rc == 0
