---
- name: Install Prometheus Operator
  kubernetes.core.helm:
    name: prometheus
    namespace: monitoring
    create_namespace: true
    chart_ref: prometheus-community/kube-prometheus-stack
    values:
      grafana:
        adminPassword: "your-secure-password"
      prometheus:
        prometheusSpec:
          serviceMonitorSelectorNilUsesHardcodedSelector: false

- name: Create NodePort services
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ item.name }}"
        namespace: monitoring
      spec:
        type: NodePort
        selector:
          matchLabels: "{{ item.selector }}"
        ports:
          - port: "{{ item.port }}"
            targetPort: "{{ item.targetPort }}"
            nodePort: "{{ item.nodePort }}"
  loop:
    - {
        name: grafana-nodeport,
        selector: { "app.kubernetes.io/name": "grafana" },
        port: 80,
        targetPort: 3000,
        nodePort: 30000,
      }
    - {
        name: prometheus-nodeport,
        selector: { "app.kubernetes.io/name": "prometheus" },
        port: 9090,
        targetPort: 9090,
        nodePort: 30001,
      }
